#!/usr/bin/with-contenv bash

echo "Starting Aria2"

if [ ! -f /conf/aria2.session ]; then
	touch /conf/aria2.session
fi

export HOME="~app"
exec s6-setuidgid app "aria2c --conf-path=/config/aria2.conf"
